[workspace]
resolver = "3"
members = [
    "crates/cancho-syntax",
    "crates/cancho-types",
    "crates/cancho-id",
    "crates/cancho-ir",
    "crates/cancho-codegen",
    "crates/cancho-codegen-llvm",
    "crates/cancho-vcs",
    "crates/cancho",
]

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
license = "EUPL-1.2"
publish = false

[workspace.dependencies]
cancho-syntax = { path = "crates/cancho-syntax" }
cancho-types = { path = "crates/cancho-types" }
cancho-id = { path = "crates/cancho-id" }
cancho-ir = { path = "crates/cancho-ir" }
cancho-codegen = { path = "crates/cancho-codegen" }
cancho-codegen-llvm = { path = "crates/cancho-codegen-llvm" }
cancho-vcs = { path = "crates/cancho-vcs" }
