//! `lex-sys repo-stats` — the mechanical facts `docsync.toml`'s
//! `repo-stats` block generates for `README.md`.
//!
//! Every number here is counted from the repository as it stands, not
//! copied from memory or a prior run. The `Net` outbound/inbound scan
//! deliberately mirrors `crates/lex-sys/tests/conformance/net.rs`'s
//! `the_network_programs_are_counted` exactly (same three directories,
//! same `extern fn` name lists) rather than approximating it, so the two
//! can never silently disagree: if a program's own `extern fn` set
//! changes, both the test and this generator move together the next time
//! `docsync` runs, and `docsync --check` is what catches a run that never
//! happened.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

/// The generated body for the `repo-stats` block — a single Markdown
/// paragraph, no trailing blank line (the caller normalizes that).
pub fn render(root: &Path) -> String {
    let crates_dir = root.join("crates");
    let (crate_count, rust_loc) = crate_stats(&crates_dir);
    let example_count = count_files_with_ext(&root.join("examples"), "ls");
    let doc_count = count_files_with_ext(&root.join("docs"), "md");
    let (outbound, inbound) = net_examples(root);

    let mut out = String::new();
    out.push_str("**Repo, by the numbers** (generated by `lex-sys docsync`, checked in CI — `docsync.toml`, `crates/lex-sys/src/repo_stats.rs`):\n");
    out.push_str(&format!(
        "{crate_count} crates under `crates/` ({rust_loc} lines of Rust), {example_count} example programs under `examples/`, {doc_count} design docs under `docs/`. "
    ));
    out.push_str(&format!(
        "`Net`: {} outbound ({}), {} inbound ({}).",
        outbound.len(),
        format_paths(&outbound),
        inbound.len(),
        format_paths(&inbound),
    ));
    out
}

fn format_paths(paths: &BTreeSet<String>) -> String {
    paths.iter().map(|p| format!("`{p}`")).collect::<Vec<_>>().join(", ")
}

/// `(crate count, total non-blank Rust source lines)` under `crates/`,
/// one directory-with-a-`Cargo.toml` per crate.
fn crate_stats(crates_dir: &Path) -> (usize, usize) {
    let Ok(entries) = std::fs::read_dir(crates_dir) else {
        return (0, 0);
    };
    let mut crate_count = 0;
    let mut total_lines = 0;
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_dir() || !path.join("Cargo.toml").exists() {
            continue;
        }
        crate_count += 1;
        total_lines += rust_lines_under(&path);
    }
    (crate_count, total_lines)
}

fn rust_lines_under(dir: &Path) -> usize {
    let mut total = 0;
    let mut stack = vec![dir.to_path_buf()];
    while let Some(at) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&at) else { continue };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                if path.file_name().is_some_and(|n| n == "target") {
                    continue;
                }
                stack.push(path);
            } else if path.extension().is_some_and(|e| e == "rs") {
                if let Ok(text) = std::fs::read_to_string(&path) {
                    total += text.lines().count();
                }
            }
        }
    }
    total
}

fn count_files_with_ext(dir: &Path, ext: &str) -> usize {
    let mut count = 0;
    let mut stack = vec![dir.to_path_buf()];
    while let Some(at) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&at) else { continue };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
            } else if path.extension().is_some_and(|e| e == ext) {
                count += 1;
            }
        }
    }
    count
}

/// The same scan `the_network_programs_are_counted` (`tests/conformance/
/// net.rs`) runs: every `.ls` file under `examples/`, `std/` and
/// `tests/accept/`, classified by which `extern fn` names it declares.
fn net_examples(root: &Path) -> (BTreeSet<String>, BTreeSet<String>) {
    let mut inbound = BTreeSet::new();
    let mut outbound = BTreeSet::new();

    let mut sources: Vec<PathBuf> = Vec::new();
    for directory in ["examples", "std", "tests/accept"] {
        let mut stack = vec![root.join(directory)];
        while let Some(at) = stack.pop() {
            let Ok(entries) = std::fs::read_dir(&at) else { continue };
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    stack.push(path);
                } else if path.extension().is_some_and(|e| e == "ls") {
                    sources.push(path);
                }
            }
        }
    }

    for path in &sources {
        let Ok(text) = std::fs::read_to_string(path) else { continue };
        let relative = path.strip_prefix(root).unwrap_or(path).display().to_string();
        for line in text.lines() {
            let Some(rest) = line.trim().strip_prefix("extern fn ") else { continue };
            let Some(name) = rest.split(['[', '(']).next() else { continue };
            let name = name.trim();
            if ["bind", "listen", "accept"].contains(&name) {
                inbound.insert(relative.clone());
            }
            if ["connect", "sendto", "getaddrinfo"].contains(&name) {
                outbound.insert(relative.clone());
            }
        }
    }
    (outbound, inbound)
}
