module selfhost.tables;

// tables.ls -- the prelude's types and the builtins, as data for the checker.
//
// GENERATED by `crates/lex-sys-ir/src/tests/selfhost_tables.rs`; do not edit. That test
// fails when this file is not what `prelude_types` and `Builtin::ALL` say, and
// `UPDATE_SELFHOST_TABLES=1 cargo test -p lex-sys-ir selfhost_tables` rewrites it.
//
// A prelude type is what the checker finds before any declaration: its name, how many
// type parameters it takes, the edition it appears in (`since`), whether another module
// may name it, and which of its parameters carry a `val` bound (bit i for parameter i).
// Its index is its `DefId`, so the order is the Rust order.

pub fn prelude_count() -> [] int {
    return 46;
}

pub fn prelude_box() -> [] int {
    return 5;
}

pub fn prelude_ffi() -> [] int {
    return 2;
}

fn prelude_chars() -> [] &static [byte] {
    return "WorldIoFfiFsHeapBoxArgsSplitFileOpenedReadNetSplitThreadListenerConnListeningAcceptedReceivedSentDialedPollerPollingClockSplitAttachedDoneSignalsSplitSignalWatchWatchingDirDirOpenedDirListListingListedDirStatExecSplitChildPipeChildEndStdioPipedSpawnedExited";
}

static prelude_starts: [int] {
    let t = alloc_slice[static](46, 0);
    t[1] = 5;
    t[2] = 7;
    t[3] = 10;
    t[4] = 12;
    t[5] = 16;
    t[6] = 19;
    t[7] = 23;
    t[8] = 28;
    t[9] = 32;
    t[10] = 38;
    t[11] = 42;
    t[12] = 45;
    t[13] = 50;
    t[14] = 56;
    t[15] = 64;
    t[16] = 68;
    t[17] = 77;
    t[18] = 85;
    t[19] = 93;
    t[20] = 97;
    t[21] = 103;
    t[22] = 109;
    t[23] = 116;
    t[24] = 121;
    t[25] = 126;
    t[26] = 134;
    t[27] = 138;
    t[28] = 145;
    t[29] = 150;
    t[30] = 161;
    t[31] = 169;
    t[32] = 172;
    t[33] = 181;
    t[34] = 188;
    t[35] = 195;
    t[36] = 201;
    t[37] = 208;
    t[38] = 212;
    t[39] = 217;
    t[40] = 222;
    t[41] = 226;
    t[42] = 234;
    t[43] = 239;
    t[44] = 244;
    t[45] = 251;
    return t;
}

static prelude_lens: [int] {
    let t = alloc_slice[static](46, 0);
    t[0] = 5;
    t[1] = 2;
    t[2] = 3;
    t[3] = 2;
    t[4] = 4;
    t[5] = 3;
    t[6] = 4;
    t[7] = 5;
    t[8] = 4;
    t[9] = 6;
    t[10] = 4;
    t[11] = 3;
    t[12] = 5;
    t[13] = 6;
    t[14] = 8;
    t[15] = 4;
    t[16] = 9;
    t[17] = 8;
    t[18] = 8;
    t[19] = 4;
    t[20] = 6;
    t[21] = 6;
    t[22] = 7;
    t[23] = 5;
    t[24] = 5;
    t[25] = 8;
    t[26] = 4;
    t[27] = 7;
    t[28] = 5;
    t[29] = 11;
    t[30] = 8;
    t[31] = 3;
    t[32] = 9;
    t[33] = 7;
    t[34] = 7;
    t[35] = 6;
    t[36] = 7;
    t[37] = 4;
    t[38] = 5;
    t[39] = 5;
    t[40] = 4;
    t[41] = 8;
    t[42] = 5;
    t[43] = 5;
    t[44] = 7;
    t[45] = 6;
    return t;
}

static prelude_arities: [int] {
    let t = alloc_slice[static](46, 0);
    t[2] = 1;
    t[3] = 1;
    t[5] = 1;
    t[11] = 1;
    t[13] = 2;
    t[27] = 1;
    t[37] = 1;
    return t;
}

static prelude_sinces: [int] {
    let t = alloc_slice[static](46, 0);
    t[0] = 1;
    t[1] = 1;
    t[2] = 1;
    t[3] = 1;
    t[4] = 1;
    t[5] = 1;
    t[6] = 1;
    t[7] = 1;
    t[8] = 1;
    t[9] = 1;
    t[10] = 1;
    t[11] = 2;
    t[12] = 2;
    t[13] = 4;
    t[14] = 5;
    t[15] = 5;
    t[16] = 5;
    t[17] = 5;
    t[18] = 5;
    t[19] = 5;
    t[20] = 5;
    t[21] = 5;
    t[22] = 5;
    t[23] = 5;
    t[24] = 5;
    t[25] = 5;
    t[26] = 5;
    t[27] = 6;
    t[28] = 6;
    t[29] = 6;
    t[30] = 6;
    t[31] = 6;
    t[32] = 6;
    t[33] = 6;
    t[34] = 6;
    t[35] = 6;
    t[36] = 6;
    t[37] = 7;
    t[38] = 7;
    t[39] = 7;
    t[40] = 7;
    t[41] = 7;
    t[42] = 7;
    t[43] = 7;
    t[44] = 7;
    t[45] = 7;
    return t;
}

static prelude_publics: [int] {
    let t = alloc_slice[static](46, 0);
    t[0] = 1;
    t[1] = 1;
    t[2] = 1;
    t[3] = 1;
    t[4] = 1;
    t[5] = 1;
    t[6] = 1;
    t[7] = 1;
    t[8] = 1;
    t[9] = 1;
    t[10] = 1;
    t[11] = 1;
    t[12] = 1;
    t[13] = 1;
    t[14] = 1;
    t[15] = 1;
    t[16] = 1;
    t[17] = 1;
    t[18] = 1;
    t[19] = 1;
    t[20] = 1;
    t[21] = 1;
    t[22] = 1;
    t[23] = 1;
    t[24] = 1;
    t[25] = 1;
    t[26] = 1;
    t[27] = 1;
    t[28] = 1;
    t[29] = 1;
    t[30] = 1;
    t[31] = 1;
    t[32] = 1;
    t[33] = 1;
    t[34] = 1;
    t[35] = 1;
    t[36] = 1;
    t[37] = 1;
    t[38] = 1;
    t[39] = 1;
    t[40] = 1;
    t[41] = 1;
    t[42] = 1;
    t[43] = 1;
    t[44] = 1;
    t[45] = 1;
    return t;
}

static prelude_bounds: [int] {
    let t = alloc_slice[static](46, 0);
    return t;
}

pub fn prelude_name(i: int) -> [] &static [byte] {
    let start = prelude_starts[i];
    return prelude_chars()[start..start + prelude_lens[i]];
}

pub fn prelude_arity(i: int) -> [] int {
    return prelude_arities[i];
}

pub fn prelude_since(i: int) -> [] int {
    return prelude_sinces[i];
}

pub fn prelude_public(i: int) -> [] bool {
    return prelude_publics[i] != 0;
}

// Bit i set: parameter i is bounded `val`.
pub fn prelude_bound(i: int) -> [] int {
    return prelude_bounds[i];
}

pub fn builtin_count() -> [] int {
    return 119;
}

fn builtin_chars() -> [] &static [byte] {
    return "putcharwrite_byteswrite_errflush_outgetcharsplitreleasenarrowfork_heapfork_clockcopy_withincopy_intoindex_of_bytewrapping_addwrapping_subwrapping_mulvalue_barrierlenbyte_ofint_offloat_oftruncateis_nansqrtbits_off32_offloat_of32bits_of32f32_of_bitssqrt32f32_of_intint_of_f32fs_readfs_writeopen_readfile_readfile_closeopen_appendopen_writeopen_newopen_rwfile_writefile_pwritefile_preadfile_syncfile_truncatefile_sizefs_renamefs_removefile_lockboxunboxcontentsarg_countargbox_sliceunbox_sliceconnectbindlistenaccepttcp_listentcp_connecttcp_connect_starttcp_acceptpoller_newpoller_add_listenerpoller_add_connpoller_modifypoller_removepoller_waitpoller_closeclock_msclock_unix_msconn_detachconn_attachconn_readconn_writeconn_nonblockingconn_nodelayconn_connect_statuslistener_nonblockingconn_closelistener_closesignals_watchsignals_pendingpoller_add_signalssignals_closeopen_dirdir_enterdir_open_readdir_closedir_open_newdir_open_appenddir_renamedir_removedir_syncdir_listdir_nextdir_list_closedir_statdir_modedir_own_modepipe_openexec_spawnexec_spawn_inchild_waitchild_killpipe_readpipe_writepipe_nonblockingpipe_closechild_end_closepoller_add_pipepoller_add_childnull_ptrspawnjointrap";
}

static builtin_starts: [int] {
    let t = alloc_slice[static](119, 0);
    t[1] = 7;
    t[2] = 18;
    t[3] = 27;
    t[4] = 36;
    t[5] = 43;
    t[6] = 48;
    t[7] = 55;
    t[8] = 61;
    t[9] = 70;
    t[10] = 80;
    t[11] = 91;
    t[12] = 100;
    t[13] = 113;
    t[14] = 125;
    t[15] = 137;
    t[16] = 149;
    t[17] = 162;
    t[18] = 165;
    t[19] = 172;
    t[20] = 178;
    t[21] = 186;
    t[22] = 194;
    t[23] = 200;
    t[24] = 204;
    t[25] = 211;
    t[26] = 217;
    t[27] = 227;
    t[28] = 236;
    t[29] = 247;
    t[30] = 253;
    t[31] = 263;
    t[32] = 273;
    t[33] = 280;
    t[34] = 288;
    t[35] = 297;
    t[36] = 306;
    t[37] = 316;
    t[38] = 327;
    t[39] = 337;
    t[40] = 345;
    t[41] = 352;
    t[42] = 362;
    t[43] = 373;
    t[44] = 383;
    t[45] = 392;
    t[46] = 405;
    t[47] = 414;
    t[48] = 423;
    t[49] = 432;
    t[50] = 441;
    t[51] = 444;
    t[52] = 449;
    t[53] = 457;
    t[54] = 466;
    t[55] = 469;
    t[56] = 478;
    t[57] = 489;
    t[58] = 496;
    t[59] = 500;
    t[60] = 506;
    t[61] = 512;
    t[62] = 522;
    t[63] = 533;
    t[64] = 550;
    t[65] = 560;
    t[66] = 570;
    t[67] = 589;
    t[68] = 604;
    t[69] = 617;
    t[70] = 630;
    t[71] = 641;
    t[72] = 653;
    t[73] = 661;
    t[74] = 674;
    t[75] = 685;
    t[76] = 696;
    t[77] = 705;
    t[78] = 715;
    t[79] = 731;
    t[80] = 743;
    t[81] = 762;
    t[82] = 782;
    t[83] = 792;
    t[84] = 806;
    t[85] = 819;
    t[86] = 834;
    t[87] = 852;
    t[88] = 865;
    t[89] = 873;
    t[90] = 882;
    t[91] = 895;
    t[92] = 904;
    t[93] = 916;
    t[94] = 931;
    t[95] = 941;
    t[96] = 951;
    t[97] = 959;
    t[98] = 967;
    t[99] = 975;
    t[100] = 989;
    t[101] = 997;
    t[102] = 1005;
    t[103] = 1017;
    t[104] = 1026;
    t[105] = 1036;
    t[106] = 1049;
    t[107] = 1059;
    t[108] = 1069;
    t[109] = 1078;
    t[110] = 1088;
    t[111] = 1104;
    t[112] = 1114;
    t[113] = 1129;
    t[114] = 1144;
    t[115] = 1160;
    t[116] = 1168;
    t[117] = 1173;
    t[118] = 1177;
    return t;
}

static builtin_lens: [int] {
    let t = alloc_slice[static](119, 0);
    t[0] = 7;
    t[1] = 11;
    t[2] = 9;
    t[3] = 9;
    t[4] = 7;
    t[5] = 5;
    t[6] = 7;
    t[7] = 6;
    t[8] = 9;
    t[9] = 10;
    t[10] = 11;
    t[11] = 9;
    t[12] = 13;
    t[13] = 12;
    t[14] = 12;
    t[15] = 12;
    t[16] = 13;
    t[17] = 3;
    t[18] = 7;
    t[19] = 6;
    t[20] = 8;
    t[21] = 8;
    t[22] = 6;
    t[23] = 4;
    t[24] = 7;
    t[25] = 6;
    t[26] = 10;
    t[27] = 9;
    t[28] = 11;
    t[29] = 6;
    t[30] = 10;
    t[31] = 10;
    t[32] = 7;
    t[33] = 8;
    t[34] = 9;
    t[35] = 9;
    t[36] = 10;
    t[37] = 11;
    t[38] = 10;
    t[39] = 8;
    t[40] = 7;
    t[41] = 10;
    t[42] = 11;
    t[43] = 10;
    t[44] = 9;
    t[45] = 13;
    t[46] = 9;
    t[47] = 9;
    t[48] = 9;
    t[49] = 9;
    t[50] = 3;
    t[51] = 5;
    t[52] = 8;
    t[53] = 9;
    t[54] = 3;
    t[55] = 9;
    t[56] = 11;
    t[57] = 7;
    t[58] = 4;
    t[59] = 6;
    t[60] = 6;
    t[61] = 10;
    t[62] = 11;
    t[63] = 17;
    t[64] = 10;
    t[65] = 10;
    t[66] = 19;
    t[67] = 15;
    t[68] = 13;
    t[69] = 13;
    t[70] = 11;
    t[71] = 12;
    t[72] = 8;
    t[73] = 13;
    t[74] = 11;
    t[75] = 11;
    t[76] = 9;
    t[77] = 10;
    t[78] = 16;
    t[79] = 12;
    t[80] = 19;
    t[81] = 20;
    t[82] = 10;
    t[83] = 14;
    t[84] = 13;
    t[85] = 15;
    t[86] = 18;
    t[87] = 13;
    t[88] = 8;
    t[89] = 9;
    t[90] = 13;
    t[91] = 9;
    t[92] = 12;
    t[93] = 15;
    t[94] = 10;
    t[95] = 10;
    t[96] = 8;
    t[97] = 8;
    t[98] = 8;
    t[99] = 14;
    t[100] = 8;
    t[101] = 8;
    t[102] = 12;
    t[103] = 9;
    t[104] = 10;
    t[105] = 13;
    t[106] = 10;
    t[107] = 10;
    t[108] = 9;
    t[109] = 10;
    t[110] = 16;
    t[111] = 10;
    t[112] = 15;
    t[113] = 15;
    t[114] = 16;
    t[115] = 8;
    t[116] = 5;
    t[117] = 4;
    t[118] = 4;
    return t;
}

static builtin_sinces: [int] {
    let t = alloc_slice[static](119, 0);
    t[0] = 1;
    t[1] = 1;
    t[2] = 1;
    t[3] = 5;
    t[4] = 1;
    t[5] = 1;
    t[6] = 1;
    t[7] = 1;
    t[8] = 4;
    t[9] = 5;
    t[10] = 5;
    t[11] = 5;
    t[12] = 5;
    t[13] = 1;
    t[14] = 1;
    t[15] = 1;
    t[16] = 6;
    t[17] = 1;
    t[18] = 1;
    t[19] = 1;
    t[20] = 1;
    t[21] = 1;
    t[22] = 1;
    t[23] = 1;
    t[24] = 1;
    t[25] = 6;
    t[26] = 6;
    t[27] = 6;
    t[28] = 6;
    t[29] = 6;
    t[30] = 6;
    t[31] = 6;
    t[32] = 1;
    t[33] = 1;
    t[34] = 1;
    t[35] = 1;
    t[36] = 1;
    t[37] = 5;
    t[38] = 5;
    t[39] = 5;
    t[40] = 5;
    t[41] = 5;
    t[42] = 5;
    t[43] = 5;
    t[44] = 5;
    t[45] = 5;
    t[46] = 5;
    t[47] = 5;
    t[48] = 5;
    t[49] = 5;
    t[50] = 1;
    t[51] = 1;
    t[52] = 1;
    t[53] = 1;
    t[54] = 1;
    t[55] = 1;
    t[56] = 1;
    t[57] = 2;
    t[58] = 2;
    t[59] = 2;
    t[60] = 2;
    t[61] = 5;
    t[62] = 5;
    t[63] = 5;
    t[64] = 5;
    t[65] = 5;
    t[66] = 5;
    t[67] = 5;
    t[68] = 5;
    t[69] = 5;
    t[70] = 5;
    t[71] = 5;
    t[72] = 5;
    t[73] = 5;
    t[74] = 5;
    t[75] = 5;
    t[76] = 5;
    t[77] = 5;
    t[78] = 5;
    t[79] = 5;
    t[80] = 5;
    t[81] = 5;
    t[82] = 5;
    t[83] = 5;
    t[84] = 6;
    t[85] = 6;
    t[86] = 6;
    t[87] = 6;
    t[88] = 6;
    t[89] = 6;
    t[90] = 6;
    t[91] = 6;
    t[92] = 6;
    t[93] = 6;
    t[94] = 6;
    t[95] = 6;
    t[96] = 6;
    t[97] = 6;
    t[98] = 6;
    t[99] = 6;
    t[100] = 6;
    t[101] = 7;
    t[102] = 7;
    t[103] = 7;
    t[104] = 7;
    t[105] = 7;
    t[106] = 7;
    t[107] = 7;
    t[108] = 7;
    t[109] = 7;
    t[110] = 7;
    t[111] = 7;
    t[112] = 7;
    t[113] = 7;
    t[114] = 7;
    t[115] = 3;
    t[116] = 4;
    t[117] = 4;
    t[118] = 1;
    return t;
}

pub fn builtin_name(i: int) -> [] &static [byte] {
    let start = builtin_starts[i];
    return builtin_chars()[start..start + builtin_lens[i]];
}

pub fn builtin_since(i: int) -> [] int {
    return builtin_sinces[i];
}
