#!/usr/bin/env python3
"""The fuzzing harnesses' fixture and seeds (docs/tls-assurance.md §3).

    python3 scripts/fuzz_corpus.py fixture          # writes tests/programs/fuzz_fixture.ls
    python3 scripts/fuzz_corpus.py seeds <dir>      # writes <dir>/<harness>/<seed>

The fixture is what every harness holds fixed, because the client's caller
chooses it and a server does not: the host name, the 96 bytes of randomness,
the time, and the trust store, which is every root the recorded handshakes in
tests/vectors/tls/ were made under. Those are the values the traces were
recorded with, so a seed cut from a trace takes the client down the path the
real server took.

The seeds are cut from the same traces and from tests/vectors/x509/, in each
harness's input format (the harness's own header says what it is).
"""
import glob
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TRACES = sorted(glob.glob(os.path.join(ROOT, "tests/vectors/tls/*_*.txt")))
TRACES = [t for t in TRACES
          if os.path.basename(t).startswith(("tlslite_", "openssl12_"))]


def start_line(path):
    for line in open(path):
        if line.startswith("C "):
            return line.split()
    raise SystemExit(f"{path}: no C line")


def server_bytes(path):
    """Each `F` line's bytes: what the server sent, as the client was fed it."""
    return [bytes.fromhex(l.split()[1]) for l in open(path)
            if l.startswith("F ") and l.split()[1] != "-"]


def lit(text):
    """A lex-sys string literal (docs/strings.md §4: six escapes)."""
    out = []
    for ch in text:
        if ch == "\n":
            out.append("\\n")
        elif ch in "\\\"":
            out.append("\\" + ch)
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            raise SystemExit(f"not printable: {ch!r}")
    return '"' + "".join(out) + '"'


def fixture():
    first = start_line(TRACES[0])
    host, random, now = first[1], first[2], first[4]
    roots = []
    for t in TRACES:
        c = start_line(t)
        if (c[1], c[2], c[4]) != (host, random, now):
            raise SystemExit(f"{t}: recorded under other parameters")
        pem = bytes.fromhex(c[3]).decode()
        if pem not in roots:
            roots.append(pem)
    out = [
        "edition 5;",
        "",
        "// Generated by `python3 scripts/fuzz_corpus.py fixture`; do not edit.",
        "// What every fuzzing harness holds fixed (docs/tls-assurance.md §3.2):",
        "// the parameters the recorded handshakes in tests/vectors/tls/ were",
        "// made with, and their roots.",
        "module fuzz_fixture;",
        "",
        "pub fn host() -> [] &static [byte] {",
        f"    return {lit(bytes.fromhex(host).decode())};",
        "}",
        "",
        "// The client's 96 bytes of randomness, as hex.",
        "pub fn random_hex() -> [] &static [byte] {",
        f"    return {lit(random)};",
        "}",
        "",
        "pub fn now() -> [] int {",
        f"    return {now};",
        "}",
        "",
        "// fuzz_flight's ServerHello records, as hex: one for each of",
        f"// {', '.join(FLIGHTS)}.",
        "pub fn server_hello_hex(which: int) -> [] &static [byte] {",
    ]
    for i, stem in enumerate(FLIGHTS):
        sh, _ = flight(stem)
        rec = bytes([22, 3, 3]) + len(sh).to_bytes(2, "big") + sh
        out.append(f"    if which == {i} {{" if i == 0 else f"    }} else if which == {i} {{")
        out.append(f"        return {lit(rec.hex())};")
    out += [
        "    }",
        '    return "";',
        "}",
        "",
        f"// {len(roots)} roots, one PEM bundle.",
        "pub fn roots() -> [] &static [byte] {",
        f"    return {lit(''.join(roots))};",
        "}",
        "",
    ]
    path = os.path.join(ROOT, "tests/programs/fuzz_fixture.ls")
    with open(path, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {path}: {len(roots)} roots")


def records(data):
    """(type, body) for each whole record in `data`."""
    out = []
    at = 0
    while at + 5 <= len(data):
        n = int.from_bytes(data[at + 3:at + 5], "big")
        out.append((data[at], data[at + 5:at + 5 + n]))
        at += 5 + n
    return out


def plaintext_messages(path):
    """The handshake messages a server sent in the clear: the ServerHello
    (and HelloRetryRequest), and in TLS 1.2 everything up to its CCS."""
    hs = b""
    for data in server_bytes(path):
        for kind, body in records(data):
            if kind == 22:
                hs += body
            elif kind == 20:
                break
    out = []
    at = 0
    while at + 4 <= len(hs):
        n = int.from_bytes(hs[at + 1:at + 4], "big")
        out.append(hs[at:at + 4 + n])
        at += 4 + n
    return out


def write(base, harness, name, data):
    d = os.path.join(base, harness)
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, name), "wb") as f:
        f.write(data)


def der_certificates():
    """Every certificate the repository's x509 vectors hold, once each: the
    corpus, its damaged copies (negative.txt), and every certificate in the
    verifier's cases, whose chains are hex-encoded PEM bundles."""
    import base64
    import re

    def pem(text):
        return [base64.b64decode(m) for m in
                re.findall(r"-----BEGIN CERTIFICATE-----(.*?)-----END", text, re.S)]

    out = []
    for path in sorted(glob.glob(os.path.join(ROOT, "tests/vectors/x509/**/*.pem"), recursive=True)):
        out += pem(open(path).read())
    for path in sorted(glob.glob(os.path.join(ROOT, "tests/vectors/x509/**/*.txt"), recursive=True)):
        for token in re.findall(r"[0-9a-f]{200,}", open(path).read()):
            if len(token) % 2:
                continue
            raw = bytes.fromhex(token)
            if raw[:1] == b"\x30":
                out.append(raw)
            elif b"BEGIN CERTIFICATE" in raw:
                out += pem(raw.decode("ascii", "replace"))
    seen = set()
    unique = []
    for der in out:
        if der not in seen:
            seen.add(der)
            unique.append(der)
    return unique


# The TLS 1.3 traces fuzz_flight starts from: one X25519 ServerHello each,
# with no HelloRetryRequest. Their ServerHellos go into the fixture.
FLIGHTS = ["tlslite_rsa", "tlslite_ecdsa", "tlslite_aes256_x25519"]


def trace(stem):
    return os.path.join(ROOT, "tests/vectors/tls", stem + ".txt")


def client_hello(path):
    """The first record the client wrote (the `=` answer to `C`)."""
    for line in open(path):
        if line.startswith("= "):
            return bytes.fromhex(line.split()[4])
    raise SystemExit(f"{path}: no ClientHello")


def expand_label(h, secret, label, context, n):
    import hashlib
    import hmac
    full = b"tls13 " + label
    info = n.to_bytes(2, "big") + bytes([len(full)]) + full + bytes([len(context)]) + context
    out, t, i = b"", b"", 1
    while len(out) < n:
        t = hmac.new(secret, t + info + bytes([i]), h).digest()
        out += t
        i += 1
    return out[:n]


def flight(stem):
    """The server's flight after its ServerHello, decrypted: a list of
    (inner content type, plaintext), and records sent in the clear as
    (0x80 | type, body). RFC 8446 §7.1's schedule, from the client's
    X25519 key (bytes 64 to 96 of the fixed randomness)."""
    import hashlib
    import hmac
    from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey, X25519PublicKey
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM, ChaCha20Poly1305

    path = trace(stem)
    random = bytes.fromhex(start_line(path)[2])
    data = b"".join(server_bytes(path))
    recs = records(data)
    kind, sh = recs[0]
    assert kind == 22 and sh[0] == 2
    suite = int.from_bytes(sh[4 + 2 + 32 + 1 + sh[4 + 2 + 32]:][:2], "big")
    at = sh.find(b"\x00\x33\x00\x24\x00\x1d\x00\x20")
    share = sh[at + 8:at + 40]
    secret = X25519PrivateKey.from_private_bytes(random[64:96]).exchange(X25519PublicKey.from_public_bytes(share))
    h = hashlib.sha384 if suite == 0x1302 else hashlib.sha256
    hl = h().digest_size
    aead = ChaCha20Poly1305 if suite == 0x1303 else AESGCM
    kl = 16 if suite == 0x1301 else 32
    ch = client_hello(path)[5:]
    transcript = ch + sh

    def extract(salt, ikm):
        return hmac.new(salt, ikm, h).digest()

    early = extract(bytes(hl), bytes(hl))
    hs = extract(expand_label(h, early, b"derived", h(b"").digest(), hl), secret)
    s_hs = expand_label(h, hs, b"s hs traffic", h(transcript).digest(), hl)
    master = extract(expand_label(h, hs, b"derived", h(b"").digest(), hl), bytes(hl))
    key, iv, seq = None, None, 0

    def keys(secret):
        return expand_label(h, secret, b"key", b"", kl), expand_label(h, secret, b"iv", b"", 12)

    key, iv = keys(s_hs)
    out = []
    finished = False
    for kind, body in recs[1:]:
        if kind != 23:
            out.append((0x80 | kind, body))
            continue
        nonce = bytes(a ^ b for a, b in zip(iv, seq.to_bytes(12, "big")))
        plain = aead(key).decrypt(nonce, body, bytes([23, 3, 3]) + len(body).to_bytes(2, "big"))
        seq += 1
        plain = plain.rstrip(b"\0")
        inner, plain = plain[-1], plain[:-1]
        out.append((inner, plain))
        if inner == 22 and not finished:
            transcript += plain
            if 20 in [m[0] for m in messages(plain)]:
                finished = True
                key, iv = keys(expand_label(h, master, b"s ap traffic", h(transcript).digest(), hl))
                seq = 0
    return sh, out


def messages(hs):
    out = []
    at = 0
    while at + 4 <= len(hs):
        n = int.from_bytes(hs[at + 1:at + 4], "big")
        out.append(hs[at:at + 4 + n])
        at += 4 + n
    return out


# fuzz_messages' first byte: which parser.
PARSERS = {2: 0, 11: 8, 12: 9, 13: 10}


def seeds(base):
    count = {}

    def put(harness, name, data):
        write(base, harness, name, data)
        count[harness] = count.get(harness, 0) + 1

    for i, der in enumerate(der_certificates()):
        put("der", f"x509_{i:03d}", der)
    for t in TRACES:
        stem = os.path.basename(t)[:-4]
        # fuzz_client: each `F` line as one feed, a 2-byte length before it.
        put("client", stem, b"".join(len(d).to_bytes(2, "big") + d for d in server_bytes(t)))
        for j, m in enumerate(plaintext_messages(t)):
            if m[0] in PARSERS:
                put("messages", f"{stem}_{j}", bytes([PARSERS[m[0]]]) + m[4:])
            if m[0] == 11:
                # A TLS 1.2 Certificate, reframed as TLS 1.3's: an empty
                # request context, and no extensions on each entry.
                body = m[4:]
                at = 3
                entries = b""
                while at < len(body):
                    n = int.from_bytes(body[at:at + 3], "big")
                    entries += body[at:at + 3 + n] + b"\0\0"
                    at += 3 + n
                put("chain", stem, b"\0" + len(entries).to_bytes(3, "big") + entries)
                put("messages", f"{stem}_{j}_13", bytes([2]) + b"\0" + len(entries).to_bytes(3, "big") + entries)
    # fuzz_flight: the trace's choice, then each record as its type, a
    # 2-byte length and its plaintext.
    for i, stem in enumerate(FLIGHTS):
        sh, out = flight(stem)
        def enc(recs):
            return bytes([i]) + b"".join(bytes([t]) + len(p).to_bytes(2, "big") + p for t, p in recs)
        put("flight", stem, enc(out))
        # The post-handshake messages no trace has: a NewSessionTicket and
        # a KeyUpdate asking for one back, before the application data.
        ticket = bytes([4]) + (24).to_bytes(3, "big") + bytes(4) + bytes(4) + b"\x01\x07" + b"\x00\x0a" + bytes(10) + b"\x00\x00"
        update = bytes([24, 0, 0, 1, 1])
        put("flight", stem + "_post", enc(out[:2] + [(22, ticket), (22, update)] + out[2:]))
    # The encrypted messages' simplest legal forms, for the parsers the
    # traces cannot seed in the clear.
    put("messages", "encrypted_extensions", bytes([1]) + b"\0\0")
    put("messages", "certificate_verify", bytes([3]) + b"\x08\x04\x00\x04abcd")
    put("messages", "finished_32", bytes([4]) + bytes(32))
    put("messages", "finished_48", bytes([5]) + bytes(48))
    put("messages", "new_session_ticket", bytes([6]) + bytes(4) + bytes(4) + b"\x01\x00" + b"\x00\x01\x00" + b"\x00\x00")
    put("messages", "key_update", bytes([7, 0]))
    print(", ".join(f"{h}: {n}" for h, n in sorted(count.items())))


if __name__ == "__main__":
    if sys.argv[1:2] == ["fixture"]:
        fixture()
    elif sys.argv[1:2] == ["seeds"] and len(sys.argv) == 3:
        seeds(sys.argv[2])
    else:
        raise SystemExit(__doc__)
