#!/usr/bin/env python3
"""Generates `std/p256_comb.cho`, the generator's tables (docs/p256-fast.md §6, §7).

    python3 scripts/p256_tables.py            # rewrites std/p256_comb.cho
    python3 scripts/p256_tables.py --check    # fails when the file is not what this prints

Two `static` tables of affine points, x then y, each coordinate in Montgomery
form (x * 2^280 mod p) as ten limbs of 28 bits, least significant first, each
limb as seven hex digits:

- `comb`: (j + 1) * 16^i * G for i in 0..64 and j in 0..7 (65 positions of a
  signed four-bit digit, eight multiples at each): 520 points, 10,400 words.
- `odd`: (2k + 1) * G for k in 0..31: the odd multiples to 63 G that wNAF
  verification of width 7 reads: 32 points, 640 words.

The points are computed here with Python's integers (affine addition) and, when
`cryptography` is installed, every one is checked against OpenSSL's scalar
multiplication of G.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "std" / "p256_comb.cho"
P = 0xFFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFF
N = 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551
GX = 0x6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296
GY = 0x4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5
BITS, LIMBS = 28, 10
R = 1 << (BITS * LIMBS)


def add(a, b):
    if a is None:
        return b
    if b is None:
        return a
    (x1, y1), (x2, y2) = a, b
    if x1 == x2:
        if (y1 + y2) % P == 0:
            return None
        lam = (3 * x1 * x1 - 3) * pow(2 * y1, -1, P) % P
    else:
        lam = (y2 - y1) * pow(x2 - x1, -1, P) % P
    x3 = (lam * lam - x1 - x2) % P
    return (x3, (lam * (x1 - x3) - y1) % P)


def mul(k, pt):
    acc = None
    while k:
        if k & 1:
            acc = add(acc, pt)
        pt = add(pt, pt)
        k >>= 1
    return acc


def limbs_hex(v):
    v = v * R % P
    return "".join(f"{(v >> (BITS * i)) & ((1 << BITS) - 1):07x}" for i in range(LIMBS))


def point_hex(pt):
    return limbs_hex(pt[0]) + limbs_hex(pt[1])


def tables():
    comb, odd = [], []
    base = (GX, GY)
    pts = []
    for i in range(65):
        row = [base]
        for j in range(1, 8):
            row.append(add(row[-1], base))
        pts += row
        comb.append("".join(point_hex(p) for p in row))
        for _ in range(4):
            base = add(base, base)
    g = (GX, GY)
    g2 = add(g, g)
    cur = g
    for k in range(32):
        odd.append(point_hex(cur))
        pts.append(cur)
        cur = add(cur, g2)
    return "".join(comb), "".join(odd), pts


def check_openssl():
    try:
        from cryptography.hazmat.primitives.asymmetric import ec
    except ImportError:
        print("cryptography is not installed: the points are not checked against OpenSSL", file=sys.stderr)
        return
    base = (GX, GY)
    n = 0
    for i in range(65):
        for j in range(8):
            k = (j + 1) * 16**i % N
            pub = ec.derive_private_key(k, ec.SECP256R1()).public_key().public_numbers()
            want = (pub.x, pub.y)
            got = mul((j + 1) * 16**i, (GX, GY))
            assert got == want, (i, j)
            n += 1
    for k in range(32):
        pub = ec.derive_private_key(2 * k + 1, ec.SECP256R1()).public_key().public_numbers()
        assert (pub.x, pub.y) == mul(2 * k + 1, (GX, GY)), k
        n += 1
    print(f"{n} table points equal OpenSSL's", file=sys.stderr)


def render():
    comb, odd, _ = tables()
    return f'''module std.p256_comb;

// GENERATED by `scripts/p256_tables.py`; do not edit. `python3 scripts/p256_tables.py --check` fails
// when this file is not what the script prints.
//
// `std.p256_comb` -- the generator's tables for `std.p256_pt` (`docs/p256-fast.md` §6, §7): affine
// points, x then y, each coordinate in Montgomery form (x * 2^280 mod p) as ten limbs of 28 bits,
// least significant first. A `static` is evaluated while compiling and is read-only data in the
// binary (`docs/compile-time-data.md`): nothing is built when a program runs.
//
// - `comb`: (j + 1) * 16^i * G, i in 0..64, j in 0..7, at word (8 i + j) * 20: the multiples a
//   signed four-bit digit selects, 65 positions of 8.
// - `odd`: (2k + 1) * G, k in 0..31, at word 20 k: the odd multiples to 63 G.

fn comb_hex() -> [] &static [byte] {{
    return "{comb}";
}}

fn odd_hex() -> [] &static [byte] {{
    return "{odd}";
}}

fn nibble(c: int) -> [] int {{
    if c >= 97 {{
        return c - 87;
    }}
    return c - 48;
}}

pub static comb: [int] {{
    let t = alloc_slice[static](10400, 0);
    let s = comb_hex();
    var i = 0;
    while i < 10400 {{
        var v = 0;
        var j = 0;
        while j < 7 {{
            v = v * 16 + nibble(int_of(s[7 * i + j]));
            j = j + 1;
        }}
        t[i] = v;
        i = i + 1;
    }}
    return t;
}}

pub static odd: [int] {{
    let t = alloc_slice[static](640, 0);
    let s = odd_hex();
    var i = 0;
    while i < 640 {{
        var v = 0;
        var j = 0;
        while j < 7 {{
            v = v * 16 + nibble(int_of(s[7 * i + j]));
            j = j + 1;
        }}
        t[i] = v;
        i = i + 1;
    }}
    return t;
}}

// Word `i` of `comb` (another module reaches a static through a function).
pub fn comb_at(i: int) -> [] int {{
    return comb[i];
}}

// Word `i` of `odd`.
pub fn odd_at(i: int) -> [] int {{
    return odd[i];
}}
'''


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        check_openssl()
        if OUT.read_text() != text:
            print("std/p256_comb.cho is not what scripts/p256_tables.py prints")
            sys.exit(1)
        print("std/p256_comb.cho is current")
    else:
        check_openssl()
        OUT.write_text(text)
        print(f"wrote {OUT} ({len(text.splitlines())} lines, {len(text)} bytes)")
