//! `examples/selfhost/tables.cho`: the prelude's types and the builtins' names, as data for the
//! checker being ported into cancho (`docs/self-hosting.md` section 6).
//!
//! The port cannot read `prelude_types` or `Builtin::ALL`, so it carries what it needs of them
//! as a generated module, and this test is what keeps it from drifting: it renders the module
//! and requires the file on disk to be it. A new prelude type or builtin fails this test until
//! the file is regenerated:
//!
//!     UPDATE_SELFHOST_TABLES=1 cargo test -p cancho-ir selfhost_tables

use crate::*;
use std::fmt::Write;

/// A type as a prefix-coded run of integers, which the port decodes into its own type table: 1 to 6 are
/// `int`, `byte`, `float`, `f32`, `bool` and `()`; 10 and 11 a shared and a unique reference, then the
/// region (a parameter's position, or 99 for `static`) and the referent; 12 a slice, then its element;
/// 13 a prelude type, then its index, how many arguments, and them; 14 a tuple, then its size and parts;
/// 15 a type parameter, then its position; 16 a literal type (what `Fs(\"/tmp\")` is narrowed to);
/// 17 `c_ptr`.
fn encode(ty: &Type, out: &mut Vec<u64>) {
    match ty {
        Type::Int => out.push(1),
        Type::Byte => out.push(2),
        Type::Float => out.push(3),
        Type::F32 => out.push(4),
        Type::Bool => out.push(5),
        Type::Unit => out.push(6),
        Type::Ref { unique, region, inner } => {
            out.push(if *unique { 11 } else { 10 });
            out.push(match region {
                Region::Param(i) => u64::from(*i),
                Region::Static => 99,
                other => panic!("a signature names the region {other:?}"),
            });
            encode(inner, out);
        }
        Type::Slice(element) => {
            out.push(12);
            encode(element, out);
        }
        Type::Tuple(parts) => {
            out.push(14);
            out.push(parts.len() as u64);
            parts.iter().for_each(|p| encode(p, out));
        }
        Type::Param(i) => {
            out.push(15);
            out.push(u64::from(*i));
        }
        Type::Named(def, args) => {
            out.push(13);
            out.push(u64::from(def.0));
            out.push(args.len() as u64);
            args.iter().for_each(|a| encode(a, out));
        }
        Type::Lit(_) => out.push(16),
        Type::CPtr => out.push(17),
        other => panic!("a signature has the type {other:?}"),
    }
}

fn table(out: &mut String, name: &str, values: Vec<u64>) {
    let _ = writeln!(out, "static {name}: [int] {{");
    let _ = writeln!(out, "    let t = alloc_slice[static]({}, 0);", values.len().max(1));
    for (i, v) in values.iter().enumerate() {
        if *v != 0 {
            let _ = writeln!(out, "    t[{i}] = {v};");
        }
    }
    out.push_str("    return t;\n}\n\n");
}

fn render() -> String {
    let ast = Ast::new();
    let mut unifier = Unifier::new();
    let defs = prelude_types(&ast, &mut unifier);

    let mut out = String::new();
    out.push_str(
        "module selfhost.tables;\n\n\
         // tables.cho -- the prelude's types and the builtins, as data for the checker.\n\
         //\n\
         // GENERATED by `crates/cancho-ir/src/tests/selfhost_tables.rs`; do not edit. That test\n\
         // fails when this file is not what `prelude_types` and `Builtin::ALL` say, and\n\
         // `UPDATE_SELFHOST_TABLES=1 cargo test -p cancho-ir selfhost_tables` rewrites it.\n\
         //\n\
         // A prelude type is what the checker finds before any declaration: its name, how many\n\
         // type parameters it takes, the edition it appears in (`since`), whether another module\n\
         // may name it, and which of its parameters carry a `val` bound (bit i for parameter i).\n\
         // Its index is its `DefId`, so the order is the Rust order.\n\n",
    );

    let names: Vec<&str> = defs.iter().map(|d| ast.name_of(d.name)).collect();
    let mut chars = String::new();
    let mut starts = Vec::new();
    let mut lens = Vec::new();
    for n in &names {
        starts.push(chars.len() as u64);
        lens.push(n.len() as u64);
        chars.push_str(n);
    }
    let _ = writeln!(out, "pub fn prelude_count() -> [] int {{\n    return {};\n}}\n", defs.len());
    let _ = writeln!(out, "pub fn prelude_box() -> [] int {{\n    return {PRELUDE_BOX};\n}}\n");
    let _ = writeln!(out, "pub fn prelude_ffi() -> [] int {{\n    return {PRELUDE_FFI};\n}}\n");
    let _ =
        writeln!(out, "fn prelude_chars() -> [] &static [byte] {{\n    return \"{chars}\";\n}}\n");
    table(&mut out, "prelude_starts", starts);
    table(&mut out, "prelude_lens", lens);
    table(&mut out, "prelude_arities", defs.iter().map(|d| d.generics.len() as u64).collect());
    table(&mut out, "prelude_sinces", defs.iter().map(|d| u64::from(d.since)).collect());
    table(&mut out, "prelude_publics", defs.iter().map(|d| u64::from(d.public)).collect());
    // The mode of a prelude type as a function of its arguments (`mode_of`, `linear.rs`): bit 0 if it
    // is `res` whatever they are, and bit 1 + i if it is `res` when argument i is. A mode is a
    // disjunction over a type's members, so probing each argument alone with a `res` type says
    // all of it.
    let res_probe = Type::Named(DefId(PRELUDE_BOX as u32), vec![Type::Int]);
    assert_eq!(mode_of(&defs, &unifier, &[], &res_probe), Mode::Res, "the probe is `res`");
    let res_bits: Vec<u64> = defs
        .iter()
        .map(|d| {
            let k = d.generics.len();
            let at = |hole: Option<usize>| {
                let args = (0..k)
                    .map(|i| if hole == Some(i) { res_probe.clone() } else { Type::Int })
                    .collect();
                mode_of(&defs, &unifier, &[], &Type::Named(d.def, args)) == Mode::Res
            };
            let mut bits = u64::from(at(None));
            for i in 0..k {
                bits |= u64::from(at(Some(i))) << (1 + i);
            }
            bits
        })
        .collect();
    table(&mut out, "prelude_res_bits", res_bits);
    // What owning a capability discharges (`discharged_by`), as the labels it yields: `name` for a
    // plain one, `name*` for one narrowed to the literal the type is written with (`Fs("/tmp")`
    // yields `fs_read("/tmp")`), `name=` for one narrowed to the empty string (the root).
    // `is_capability` is a flag per type: the foreign boundary lets a borrowed one cross.
    let probe = "\u{1}";
    let labels: Vec<String> = defs
        .iter()
        .map(|d| {
            let args = vec![Type::Lit(probe.to_owned()); d.generics.len()];
            let ty = Type::Named(d.def, args);
            discharged_by(&defs, &ty)
                .labels()
                .iter()
                .map(|l| match l.argument.as_deref() {
                    None => l.name.clone(),
                    Some(a) if a == probe => format!("{}*", l.name),
                    Some("") => format!("{}=", l.name),
                    Some(other) => panic!("`{}` is narrowed to `{other}`", l.name),
                })
                .collect::<Vec<_>>()
                .join(" ")
        })
        .collect();
    let mut label_chars = String::new();
    let (mut label_starts, mut label_lens) = (Vec::new(), Vec::new());
    for l in &labels {
        label_starts.push(label_chars.len() as u64);
        label_lens.push(l.len() as u64);
        label_chars.push_str(l);
    }
    let _ = writeln!(
        out,
        "fn prelude_label_chars() -> [] &static [byte] {{\n    return \"{label_chars}\";\n}}\n"
    );
    table(&mut out, "prelude_label_starts", label_starts);
    table(&mut out, "prelude_label_lens", label_lens);
    table(
        &mut out,
        "prelude_capabilities",
        defs.iter().map(|d| u64::from(is_capability(d.def))).collect(),
    );
    table(
        &mut out,
        "prelude_bounds",
        defs.iter()
            .map(|d| {
                (0..d.generics.len())
                    .filter(|i| d.bound(*i) == Some(Mode::Val))
                    .fold(0u64, |bits, i| bits | (1 << i))
            })
            .collect(),
    );
    out.push_str(
        "pub fn prelude_name(i: int) -> [] &static [byte] {\n    let start = prelude_starts[i];\n    \
         return prelude_chars()[start..start + prelude_lens[i]];\n}\n\n\
         pub fn prelude_arity(i: int) -> [] int {\n    return prelude_arities[i];\n}\n\n\
         pub fn prelude_since(i: int) -> [] int {\n    return prelude_sinces[i];\n}\n\n\
         pub fn prelude_public(i: int) -> [] bool {\n    return prelude_publics[i] != 0;\n}\n\n\
         pub fn prelude_res(i: int) -> [] int {\n    return prelude_res_bits[i];\n}\n\n\
         // What owning the capability discharges: labels separated by spaces, each `name`, `name*`\n\
         // (narrowed to the literal the type is written with) or `name=` (narrowed to the empty string).\n\
         pub fn prelude_labels(i: int) -> [] &static [byte] {\n    let start = prelude_label_starts[i];\n    \
         return prelude_label_chars()[start..start + prelude_label_lens[i]];\n}\n\n\
         // Is it a capability, which a foreign function may borrow?\n\
         pub fn prelude_capability(i: int) -> [] bool {\n    return prelude_capabilities[i] != 0;\n}\n\n\
         // Bit i set: parameter i is bounded `val`.\n\
         pub fn prelude_bound(i: int) -> [] int {\n    return prelude_bounds[i];\n}\n\n",
    );

    let builtins: Vec<(&str, u64)> =
        Builtin::ALL.iter().map(|b| (b.name(), u64::from(b.since()))).collect();
    let mut chars = String::new();
    let mut starts = Vec::new();
    let mut lens = Vec::new();
    for (n, _) in &builtins {
        starts.push(chars.len() as u64);
        lens.push(n.len() as u64);
        chars.push_str(n);
    }
    let _ =
        writeln!(out, "pub fn builtin_count() -> [] int {{\n    return {};\n}}\n", builtins.len());
    let _ =
        writeln!(out, "fn builtin_chars() -> [] &static [byte] {{\n    return \"{chars}\";\n}}\n");
    table(&mut out, "builtin_starts", starts);
    table(&mut out, "builtin_lens", lens);
    table(&mut out, "builtin_sinces", builtins.iter().map(|(_, s)| *s).collect());
    out.push_str(
        "pub fn builtin_name(i: int) -> [] &static [byte] {\n    let start = builtin_starts[i];\n    \
         return builtin_chars()[start..start + builtin_lens[i]];\n}\n\n\
         pub fn builtin_since(i: int) -> [] int {\n    return builtin_sinces[i];\n}\n",
    );

    out
}

/// `examples/selfhost/builtins.cho`: what the builtins take, answer and perform, and the fields of the
/// prelude's structs, as data for the checker. Kept apart from `tables.cho` for the file-length limit.
fn render_signatures() -> String {
    let ast = Ast::new();
    let mut unifier = Unifier::new();
    let defs = prelude_types(&ast, &mut unifier);
    let mut out = String::new();
    out.push_str(
        "module selfhost.builtins;\n\n\
         // builtins.cho -- the builtins' signatures and effects, and the prelude structs' fields.\n\
         //\n\
         // GENERATED by `crates/cancho-ir/src/tests/selfhost_tables.rs`; do not edit. That test fails when\n\
         // this file is not what `Builtin::signature`, `Builtin::effects` and `prelude_types` say, and\n\
         // `UPDATE_SELFHOST_TABLES=1 cargo test -p cancho-ir selfhost_tables` rewrites it.\n\n",
    );

    // What each builtin takes, answers and performs. `builtin_sigs` holds, for builtin b from
    // `builtin_sig_starts[b]`: 1 if the lowering checks it by hand (its table signature is `() -> ()`),
    // else 0; how many parameters; each parameter's type and then the result's, as `encode` writes them.
    // `builtin_regions` is how many region parameters it has.
    let prelude_ids: Vec<DefId> = defs.iter().map(|d| d.def).collect();
    let mut sigs: Vec<u64> = Vec::new();
    let mut sig_starts = Vec::new();
    let mut regions = Vec::new();
    let mut effect_names: Vec<String> = Vec::new();
    let mut effect_stream: Vec<u64> = Vec::new();
    let (mut effect_starts, mut effect_counts) = (Vec::new(), Vec::new());
    for b in Builtin::ALL {
        let (params, ret) = b.signature(&prelude_ids);
        sig_starts.push(sigs.len() as u64);
        regions.push(b.regions() as u64);
        sigs.push(u64::from(params.is_empty() && ret == Type::Unit));
        sigs.push(params.len() as u64);
        for p in &params {
            encode(p, &mut sigs);
        }
        encode(&ret, &mut sigs);
        effect_starts.push(effect_stream.len() as u64);
        let labels = b.effects();
        effect_counts.push(labels.labels().len() as u64);
        for l in labels.labels() {
            let at = effect_names.iter().position(|n| *n == l.name).unwrap_or_else(|| {
                effect_names.push(l.name.clone());
                effect_names.len() - 1
            });
            effect_stream.push(at as u64 * 2 + u64::from(l.argument.is_some()));
        }
    }
    table(&mut out, "builtin_sigs", sigs);
    table(&mut out, "builtin_sig_starts", sig_starts);
    table(&mut out, "builtin_region_counts", regions);
    table(&mut out, "builtin_effect_stream", effect_stream);
    table(&mut out, "builtin_effect_starts", effect_starts);
    table(&mut out, "builtin_effect_counts", effect_counts);
    let mut effect_chars = String::new();
    let (mut effect_name_starts, mut effect_name_lens) = (Vec::new(), Vec::new());
    for n in &effect_names {
        effect_name_starts.push(effect_chars.len() as u64);
        effect_name_lens.push(n.len() as u64);
        effect_chars.push_str(n);
    }
    let _ = writeln!(
        out,
        "fn effect_chars() -> [] &static [byte] {{\n    return \"{effect_chars}\";\n}}\n"
    );
    table(&mut out, "effect_name_starts", effect_name_starts);
    table(&mut out, "effect_name_lens", effect_name_lens);
    let _ = writeln!(
        out,
        "pub fn effect_count() -> [] int {{\n    return {};\n}}\n",
        effect_names.len()
    );

    // The fields of the prelude's structs (the `Split`s are the ones with any): for type d, how many,
    // and the position of its first among all of them; each field's name and its type's `encode`.
    let (mut field_counts, mut field_firsts) = (Vec::new(), Vec::new());
    let mut field_chars = String::new();
    let (mut field_name_starts, mut field_name_lens, mut field_type_starts) =
        (Vec::new(), Vec::new(), Vec::new());
    let mut field_types: Vec<u64> = Vec::new();
    for d in &defs {
        field_firsts.push(field_name_starts.len() as u64);
        match &d.kind {
            DefKind::Struct(fields) => {
                field_counts.push(fields.len() as u64);
                for (name, ty) in fields {
                    let text = ast.name_of(*name);
                    field_name_starts.push(field_chars.len() as u64);
                    field_name_lens.push(text.len() as u64);
                    field_chars.push_str(text);
                    field_type_starts.push(field_types.len() as u64);
                    encode(ty, &mut field_types);
                }
            }
            DefKind::Enum(_) => field_counts.push(0),
        }
    }
    let _ = writeln!(
        out,
        "fn field_chars() -> [] &static [byte] {{\n    return \"{field_chars}\";\n}}\n"
    );
    table(&mut out, "prelude_field_counts", field_counts);
    table(&mut out, "prelude_field_firsts", field_firsts);
    table(&mut out, "field_name_starts", field_name_starts);
    table(&mut out, "field_name_lens", field_name_lens);
    table(&mut out, "field_type_starts", field_type_starts);
    table(&mut out, "field_types", field_types);
    // The `Split` a file of an edition gets: the edition decides (`split` in `lower/net.rs`).
    let _ = writeln!(
        out,
        "pub fn split_for(edition: int) -> [] int {{\n    if edition >= 7 {{\n        return {PRELUDE_SPLIT_EXEC};\n    }}\n    \
         if edition >= 6 {{\n        return {PRELUDE_SPLIT_SIGNALS};\n    }}\n    \
         if edition >= 5 {{\n        return {PRELUDE_SPLIT_CLOCK};\n    }}\n    \
         if edition >= 2 {{\n        return {PRELUDE_SPLIT_NET};\n    }}\n    \
         return {PRELUDE_SPLIT};\n}}\n"
    );
    out.push_str(
        "pub fn builtin_sig(i: int) -> [] int {\n    return builtin_sigs[i];\n}\n\n\
         // Where builtin b's signature starts in `builtin_sig`.\n\
         pub fn builtin_sig_start(b: int) -> [] int {\n    return builtin_sig_starts[b];\n}\n\n\
         pub fn builtin_regions(b: int) -> [] int {\n    return builtin_region_counts[b];\n}\n\n\
         // How many labels builtin b performs, and label k of them as 2 * the label's number, plus 1 if it\n\
         // carries an argument (a path, a host).\n\
         pub fn builtin_effect_count(b: int) -> [] int {\n    return builtin_effect_counts[b];\n}\n\n\
         pub fn builtin_effect(b: int, k: int) -> [] int {\n    return builtin_effect_stream[builtin_effect_starts[b] + k];\n}\n\n\
         pub fn effect_name(i: int) -> [] &static [byte] {\n    let start = effect_name_starts[i];\n    \
         return effect_chars()[start..start + effect_name_lens[i]];\n}\n\n\
         pub fn prelude_field_count(d: int) -> [] int {\n    return prelude_field_counts[d];\n}\n\n\
         // Field k of prelude struct d is field number `prelude_field_first(d) + k` of all.\n\
         pub fn prelude_field_first(d: int) -> [] int {\n    return prelude_field_firsts[d];\n}\n\n\
         pub fn field_name(f: int) -> [] &static [byte] {\n    let start = field_name_starts[f];\n    \
         return field_chars()[start..start + field_name_lens[f]];\n}\n\n\
         // Where field f's type starts in `field_type`.\n\
         pub fn field_type_start(f: int) -> [] int {\n    return field_type_starts[f];\n}\n\n\
         pub fn field_type(i: int) -> [] int {\n    return field_types[i];\n}\n",
    );
    out
}

#[test]
fn selfhost_tables_are_what_the_prelude_and_the_builtins_say() {
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../examples/selfhost");
    for (file, expected) in [("tables.cho", render()), ("builtins.cho", render_signatures())] {
        let path = dir.join(file);
        if std::env::var_os("UPDATE_SELFHOST_TABLES").is_some() {
            std::fs::write(&path, &expected).expect("a writable examples/selfhost");
            continue;
        }
        let on_disk = std::fs::read_to_string(&path).unwrap_or_default();
        assert!(
            on_disk == expected,
            "examples/selfhost/{file} is out of date: run \
             `UPDATE_SELFHOST_TABLES=1 cargo test -p cancho-ir selfhost_tables`"
        );
    }
}
