//! `examples/selfhost/tables.cho`: the prelude's types and the builtins' names, as data for the
//! checker being ported into cancho (`docs/self-hosting.md` section 6).
//!
//! The port cannot read `prelude_types` or `Builtin::ALL`, so it carries what it needs of them
//! as a generated module, and this test is what keeps it from drifting: it renders the module
//! and requires the file on disk to be it. A new prelude type or builtin fails this test until
//! the file is regenerated:
//!
//!     UPDATE_SELFHOST_TABLES=1 cargo test -p cancho-ir selfhost_tables

use crate::*;
use std::fmt::Write;

fn render() -> String {
    let ast = Ast::new();
    let mut unifier = Unifier::new();
    let defs = prelude_types(&ast, &mut unifier);

    let mut out = String::new();
    out.push_str(
        "module selfhost.tables;\n\n\
         // tables.cho -- the prelude's types and the builtins, as data for the checker.\n\
         //\n\
         // GENERATED by `crates/cancho-ir/src/tests/selfhost_tables.rs`; do not edit. That test\n\
         // fails when this file is not what `prelude_types` and `Builtin::ALL` say, and\n\
         // `UPDATE_SELFHOST_TABLES=1 cargo test -p cancho-ir selfhost_tables` rewrites it.\n\
         //\n\
         // A prelude type is what the checker finds before any declaration: its name, how many\n\
         // type parameters it takes, the edition it appears in (`since`), whether another module\n\
         // may name it, and which of its parameters carry a `val` bound (bit i for parameter i).\n\
         // Its index is its `DefId`, so the order is the Rust order.\n\n",
    );

    let table = |out: &mut String, name: &str, values: Vec<u64>| {
        let _ = writeln!(out, "static {name}: [int] {{");
        let _ = writeln!(out, "    let t = alloc_slice[static]({}, 0);", values.len().max(1));
        for (i, v) in values.iter().enumerate() {
            if *v != 0 {
                let _ = writeln!(out, "    t[{i}] = {v};");
            }
        }
        out.push_str("    return t;\n}\n\n");
    };

    let names: Vec<&str> = defs.iter().map(|d| ast.name_of(d.name)).collect();
    let mut chars = String::new();
    let mut starts = Vec::new();
    let mut lens = Vec::new();
    for n in &names {
        starts.push(chars.len() as u64);
        lens.push(n.len() as u64);
        chars.push_str(n);
    }
    let _ = writeln!(out, "pub fn prelude_count() -> [] int {{\n    return {};\n}}\n", defs.len());
    let _ = writeln!(out, "pub fn prelude_box() -> [] int {{\n    return {PRELUDE_BOX};\n}}\n");
    let _ = writeln!(out, "pub fn prelude_ffi() -> [] int {{\n    return {PRELUDE_FFI};\n}}\n");
    let _ =
        writeln!(out, "fn prelude_chars() -> [] &static [byte] {{\n    return \"{chars}\";\n}}\n");
    table(&mut out, "prelude_starts", starts);
    table(&mut out, "prelude_lens", lens);
    table(&mut out, "prelude_arities", defs.iter().map(|d| d.generics.len() as u64).collect());
    table(&mut out, "prelude_sinces", defs.iter().map(|d| u64::from(d.since)).collect());
    table(&mut out, "prelude_publics", defs.iter().map(|d| u64::from(d.public)).collect());
    // The mode of a prelude type as a function of its arguments (`mode_of`, `linear.rs`): bit 0 if it
    // is `res` whatever they are, and bit 1 + i if it is `res` when argument i is. A mode is a
    // disjunction over a type's members, so probing each argument alone with a `res` type says
    // all of it.
    let res_probe = Type::Named(DefId(PRELUDE_BOX as u32), vec![Type::Int]);
    assert_eq!(mode_of(&defs, &unifier, &[], &res_probe), Mode::Res, "the probe is `res`");
    let res_bits: Vec<u64> = defs
        .iter()
        .map(|d| {
            let k = d.generics.len();
            let at = |hole: Option<usize>| {
                let args = (0..k)
                    .map(|i| if hole == Some(i) { res_probe.clone() } else { Type::Int })
                    .collect();
                mode_of(&defs, &unifier, &[], &Type::Named(d.def, args)) == Mode::Res
            };
            let mut bits = u64::from(at(None));
            for i in 0..k {
                bits |= u64::from(at(Some(i))) << (1 + i);
            }
            bits
        })
        .collect();
    table(&mut out, "prelude_res_bits", res_bits);
    // What owning a capability discharges (`discharged_by`), as the labels it yields: `name` for a
    // plain one, `name*` for one narrowed to the literal the type is written with (`Fs("/tmp")`
    // yields `fs_read("/tmp")`), `name=` for one narrowed to the empty string (the root).
    // `is_capability` is a flag per type: the foreign boundary lets a borrowed one cross.
    let probe = "\u{1}";
    let labels: Vec<String> = defs
        .iter()
        .map(|d| {
            let args = vec![Type::Lit(probe.to_owned()); d.generics.len()];
            let ty = Type::Named(d.def, args);
            discharged_by(&defs, &ty)
                .labels()
                .iter()
                .map(|l| match l.argument.as_deref() {
                    None => l.name.clone(),
                    Some(a) if a == probe => format!("{}*", l.name),
                    Some("") => format!("{}=", l.name),
                    Some(other) => panic!("`{}` is narrowed to `{other}`", l.name),
                })
                .collect::<Vec<_>>()
                .join(" ")
        })
        .collect();
    let mut label_chars = String::new();
    let (mut label_starts, mut label_lens) = (Vec::new(), Vec::new());
    for l in &labels {
        label_starts.push(label_chars.len() as u64);
        label_lens.push(l.len() as u64);
        label_chars.push_str(l);
    }
    let _ = writeln!(
        out,
        "fn prelude_label_chars() -> [] &static [byte] {{\n    return \"{label_chars}\";\n}}\n"
    );
    table(&mut out, "prelude_label_starts", label_starts);
    table(&mut out, "prelude_label_lens", label_lens);
    table(
        &mut out,
        "prelude_capabilities",
        defs.iter().map(|d| u64::from(is_capability(d.def))).collect(),
    );
    table(
        &mut out,
        "prelude_bounds",
        defs.iter()
            .map(|d| {
                (0..d.generics.len())
                    .filter(|i| d.bound(*i) == Some(Mode::Val))
                    .fold(0u64, |bits, i| bits | (1 << i))
            })
            .collect(),
    );
    out.push_str(
        "pub fn prelude_name(i: int) -> [] &static [byte] {\n    let start = prelude_starts[i];\n    \
         return prelude_chars()[start..start + prelude_lens[i]];\n}\n\n\
         pub fn prelude_arity(i: int) -> [] int {\n    return prelude_arities[i];\n}\n\n\
         pub fn prelude_since(i: int) -> [] int {\n    return prelude_sinces[i];\n}\n\n\
         pub fn prelude_public(i: int) -> [] bool {\n    return prelude_publics[i] != 0;\n}\n\n\
         pub fn prelude_res(i: int) -> [] int {\n    return prelude_res_bits[i];\n}\n\n\
         // What owning the capability discharges: labels separated by spaces, each `name`, `name*`\n\
         // (narrowed to the literal the type is written with) or `name=` (narrowed to the empty string).\n\
         pub fn prelude_labels(i: int) -> [] &static [byte] {\n    let start = prelude_label_starts[i];\n    \
         return prelude_label_chars()[start..start + prelude_label_lens[i]];\n}\n\n\
         // Is it a capability, which a foreign function may borrow?\n\
         pub fn prelude_capability(i: int) -> [] bool {\n    return prelude_capabilities[i] != 0;\n}\n\n\
         // Bit i set: parameter i is bounded `val`.\n\
         pub fn prelude_bound(i: int) -> [] int {\n    return prelude_bounds[i];\n}\n\n",
    );

    let builtins: Vec<(&str, u64)> =
        Builtin::ALL.iter().map(|b| (b.name(), u64::from(b.since()))).collect();
    let mut chars = String::new();
    let mut starts = Vec::new();
    let mut lens = Vec::new();
    for (n, _) in &builtins {
        starts.push(chars.len() as u64);
        lens.push(n.len() as u64);
        chars.push_str(n);
    }
    let _ =
        writeln!(out, "pub fn builtin_count() -> [] int {{\n    return {};\n}}\n", builtins.len());
    let _ =
        writeln!(out, "fn builtin_chars() -> [] &static [byte] {{\n    return \"{chars}\";\n}}\n");
    table(&mut out, "builtin_starts", starts);
    table(&mut out, "builtin_lens", lens);
    table(&mut out, "builtin_sinces", builtins.iter().map(|(_, s)| *s).collect());
    out.push_str(
        "pub fn builtin_name(i: int) -> [] &static [byte] {\n    let start = builtin_starts[i];\n    \
         return builtin_chars()[start..start + builtin_lens[i]];\n}\n\n\
         pub fn builtin_since(i: int) -> [] int {\n    return builtin_sinces[i];\n}\n",
    );
    out
}

#[test]
fn selfhost_tables_are_what_the_prelude_and_the_builtins_say() {
    let path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../examples/selfhost/tables.cho");
    let expected = render();
    if std::env::var_os("UPDATE_SELFHOST_TABLES").is_some() {
        std::fs::write(&path, &expected).expect("a writable examples/selfhost/tables.cho");
        return;
    }
    let on_disk = std::fs::read_to_string(&path).unwrap_or_default();
    assert!(
        on_disk == expected,
        "examples/selfhost/tables.cho is out of date: run \
         `UPDATE_SELFHOST_TABLES=1 cargo test -p cancho-ir selfhost_tables`"
    );
}
